name: code-style

on: [ push, pull_request ]

permissions: write-all

jobs:
    style:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout code
                uses: actions/checkout@v3

            -   name: Checking PHP Syntax
                uses: TheDragonCode/codestyler@v3
                with:
                    github_token: ${{ secrets.COMPOSER_TOKEN }}
                    fix: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
