name: Code Style

on: [ push, pull_request ]

permissions: write-all

jobs:
    style:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Check the code style
                uses: TheDragonCode/codestyler@v4
                if: ${{ github.event_name != 'push' || github.ref != 'refs/heads/14.x' }}

            -   name: Fix the code style
                uses: TheDragonCode/codestyler@v4
                if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/14.x' }}
                with:
                    github_token: ${{ secrets.COMPOSER_TOKEN }}
                    fix: true
