name: download

on:
    schedule:
        -   cron: 0 1 * * *
    workflow_dispatch:

permissions: write-all

jobs:
    laravel:
        uses: Laravel-Lang/.github/.github/workflows/download.yml@main
        strategy:
            fail-fast: true
            matrix:
                version: [ "9.x", "master" ]
        with:
            project: Laravel Framework ${{ matrix.version }}
            paths: source/laravel/${{ matrix.version }}/*,source/framework/${{ matrix.version }}/*
            commands: |
                vendor/bin/lang download \
                    --url=https://github.com/laravel/laravel/archive/refs/heads/${{ matrix.version }}.zip \
                    --project=laravel \
                    --ver=${{ matrix.version }} \
                    --copy=lang
                
                vendor/bin/lang download \
                    --url=https://github.com/laravel/framework/archive/refs/heads/${{ matrix.version }}.zip \
                    --project=framework \
                    --ver=${{ matrix.version }}
    
    lumen:
        uses: Laravel-Lang/.github/.github/workflows/download.yml@main
        strategy:
            fail-fast: true
            matrix:
                version: [ "9.x", "master" ]
        with:
            project: Lumen Framework ${{ matrix.version }}
            paths: source/lumen-framework/${{ matrix.version }}/*
            commands: |
                vendor/bin/lang download \
                    --url=https://github.com/laravel/lumen-framework/archive/refs/heads/${{ matrix.version }}.zip \
                    --project=lumen-framework \
                    --ver=${{ matrix.version }} \
                    --copy=lang \
                    --copy=resources/lang

    breeze:
        uses: Laravel-Lang/.github/.github/workflows/download.yml@main
        strategy:
            fail-fast: true
            matrix:
                version: [ "1.x", "master" ]
        with:
            project: Laravel Breeze ${{ matrix.version }}
            paths: source/breeze/${{ matrix.version }}/*
            commands: |
                vendor/bin/lang download \
                    --url=https://github.com/laravel/breeze/archive/refs/heads/${{ matrix.version }}.zip \
                    --project=breeze \
                    --ver=${{ matrix.version }}

    cashier_stripe:
        uses: Laravel-Lang/.github/.github/workflows/download.yml@main
        strategy:
            fail-fast: true
            matrix:
                version: [ "12.x", "13.x", "14.x", "master" ]
        with:
            project: Laravel Cashier Stripe ${{ matrix.version }}
            paths: source/cashier/stripe/${{ matrix.version }}/*
            commands: |
                vendor/bin/lang download \
                    --url=https://github.com/laravel/cashier-stripe/archive/refs/heads/${{ matrix.version }}.zip \
                    --project=cashier/stripe \
                    --ver=${{ matrix.version }}

    fortify:
        uses: Laravel-Lang/.github/.github/workflows/download.yml@main
        strategy:
            fail-fast: true
            matrix:
                version: [ "1.x", "master" ]
        with:
            project: Laravel Fortify ${{ matrix.version }}
            paths: source/fortify/${{ matrix.version }}/*
            commands: |
                vendor/bin/lang download \
                    --url=https://github.com/laravel/fortify/archive/refs/heads/${{ matrix.version }}.zip \
                    --project=fortify \
                    --ver=${{ matrix.version }}

    jetstream:
        uses: Laravel-Lang/.github/.github/workflows/download.yml@main
        strategy:
            fail-fast: true
            matrix:
                version: [ "1.x", "2.x", "master" ]
        with:
            project: Laravel Jetstream ${{ matrix.version }}
            paths: source/jetstream/${{ matrix.version }}/*
            commands: |
                vendor/bin/lang download \
                    --url=https://github.com/laravel/jetstream/archive/refs/heads/${{ matrix.version }}.zip \
                    --project=jetstream \
                    --ver=${{ matrix.version }}

    nova_log_viewer:
        uses: Laravel-Lang/.github/.github/workflows/download.yml@main
        strategy:
            fail-fast: true
            matrix:
                version: [ "main" ]
        with:
            project: Laravel Nova Log Viewer ${{ matrix.version }}
            paths: source/nova/log-viewer/${{ matrix.version }}/*
            commands: |
                vendor/bin/lang download \
                    --url=https://github.com/laravel/nova-log-viewer/archive/refs/heads/${{ matrix.version }}.zip \
                    --project=nova/log-viewer \
                    --ver=${{ matrix.version }}

    spark_aurelius:
        uses: Laravel-Lang/.github/.github/workflows/download.yml@main
        strategy:
            fail-fast: true
            matrix:
                version: [ "11.x", "12.x", "master" ]
        with:
            project: Laravel Spark Aurelius ${{ matrix.version }}
            paths: source/spark/aurelius/${{ matrix.version }}/*
            commands: |
                vendor/bin/lang download \
                    --url=https://github.com/laravel/spark-aurelius/archive/refs/heads/${{ matrix.version }}.zip \
                    --project=spark/aurelius \
                    --ver=${{ matrix.version }} \
                    --copy=install-stubs/resources/lang \
                    --only-copy

    spark_aurelius_mollie:
        uses: Laravel-Lang/.github/.github/workflows/download.yml@main
        strategy:
            fail-fast: true
            matrix:
                version: [ "v2" ]
        with:
            project: Laravel Spark Aurelius Mollie ${{ matrix.version }}
            paths: source/spark/aurelius-mollie/${{ matrix.version }}/*
            commands: |
                vendor/bin/lang download \
                    --url=https://github.com/laravel/spark-aurelius-mollie/archive/refs/heads/${{ matrix.version }}.zip \
                    --project=spark/aurelius-mollie \
                    --ver=${{ matrix.version }} \
                    --copy=install-stubs/resources/lang \
                    --only-copy

    ui:
        uses: Laravel-Lang/.github/.github/workflows/download.yml@main
        strategy:
            fail-fast: true
            matrix:
                version: [ "3.x", "4.x", "master" ]
        with:
            project: Laravel UI ${{ matrix.version }}
            paths: source/ui/${{ matrix.version }}/*
            commands: |
                vendor/bin/lang download \
                    --url=https://github.com/laravel/ui/archive/refs/heads/${{ matrix.version }}.zip \
                    --project=ui \
                    --ver=${{ matrix.version }}
