name: download

on:
    schedule:
        -   cron: 34 0 * * *
    workflow_dispatch:

permissions: write-all

jobs:
    laravel_10:
        uses: Laravel-Lang/.github/.github/workflows/download.yml@main
        strategy:
            fail-fast: true
            matrix:
                version: [ "10.x", "master" ]
        with:
            project: Laravel Framework ${{ matrix.version }}
            paths: source/framework/${{ matrix.version }}/*
            commands: |
                vendor/bin/lang download \
                    --url=https://github.com/laravel/framework/archive/refs/heads/${{ matrix.version }}.zip \
                    --project=framework \
                    --ver=${{ matrix.version }} \
                    --copy=src/Illuminate/Translation/lang

    laravel_9:
        uses: Laravel-Lang/.github/.github/workflows/download.yml@main
        strategy:
            fail-fast: true
            matrix:
                version: [ "9.x" ]
        with:
            project: Laravel Framework ${{ matrix.version }}
            paths: source/laravel/${{ matrix.version }}/*,source/framework/${{ matrix.version }}/*
            commands: |
                vendor/bin/lang download \
                    --url=https://github.com/laravel/laravel/archive/refs/heads/${{ matrix.version }}.zip \
                    --project=laravel \
                    --ver=${{ matrix.version }} \
                    --copy=lang
                
                vendor/bin/lang download \
                    --url=https://github.com/laravel/framework/archive/refs/heads/${{ matrix.version }}.zip \
                    --project=framework \
                    --ver=${{ matrix.version }} \
                    --copy=src/Illuminate/Translation/lang
    
    lumen:
        uses: Laravel-Lang/.github/.github/workflows/download.yml@main
        strategy:
            fail-fast: true
            matrix:
                version: [ "9.x", "10.x", "master" ]
        with:
            project: Lumen Framework ${{ matrix.version }}
            paths: source/lumen-framework/${{ matrix.version }}/*
            commands: |
                vendor/bin/lang download \
                    --url=https://github.com/laravel/lumen-framework/archive/refs/heads/${{ matrix.version }}.zip \
                    --project=lumen-framework \
                    --ver=${{ matrix.version }} \
                    --copy=lang \
                    --copy=resources/lang \
                    --copy=src/Illuminate/Translation/lang

    breeze:
        uses: Laravel-Lang/.github/.github/workflows/download.yml@main
        strategy:
            fail-fast: true
            matrix:
                version: [ "1.x", "master" ]
        with:
            project: Laravel Breeze ${{ matrix.version }}
            paths: source/breeze/${{ matrix.version }}/*
            commands: |
                vendor/bin/lang download \
                    --url=https://github.com/laravel/breeze/archive/refs/heads/${{ matrix.version }}.zip \
                    --project=breeze \
                    --ver=${{ matrix.version }}

    cashier_stripe:
        uses: Laravel-Lang/.github/.github/workflows/download.yml@main
        strategy:
            fail-fast: true
            matrix:
                version: [ "12.x", "13.x", "14.x", "master" ]
        with:
            project: Laravel Cashier Stripe ${{ matrix.version }}
            paths: source/cashier/stripe/${{ matrix.version }}/*
            commands: |
                vendor/bin/lang download \
                    --url=https://github.com/laravel/cashier-stripe/archive/refs/heads/${{ matrix.version }}.zip \
                    --project=cashier/stripe \
                    --ver=${{ matrix.version }}

    fortify:
        uses: Laravel-Lang/.github/.github/workflows/download.yml@main
        strategy:
            fail-fast: true
            matrix:
                version: [ "1.x", "master" ]
        with:
            project: Laravel Fortify ${{ matrix.version }}
            paths: source/fortify/${{ matrix.version }}/*
            commands: |
                vendor/bin/lang download \
                    --url=https://github.com/laravel/fortify/archive/refs/heads/${{ matrix.version }}.zip \
                    --project=fortify \
                    --ver=${{ matrix.version }}

    jetstream:
        uses: Laravel-Lang/.github/.github/workflows/download.yml@main
        strategy:
            fail-fast: true
            matrix:
                version: [ "1.x", "2.x", "3.x", "master" ]
        with:
            project: Laravel Jetstream ${{ matrix.version }}
            paths: source/jetstream/${{ matrix.version }}/*
            commands: |
                vendor/bin/lang download \
                    --url=https://github.com/laravel/jetstream/archive/refs/heads/${{ matrix.version }}.zip \
                    --project=jetstream \
                    --ver=${{ matrix.version }}

    nova:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: true
            matrix:
                nova:
                    - { branch: "3.x", version: "3.0" }
                    - { branch: "4.x", version: "4.0" }
        
        name: nova (${{ matrix.nova.branch }})

        steps:
            -   name: Checkout code
                uses: actions/checkout@v3

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    extensions: curl, mbstring, zip, pcntl, pdo, pdo_sqlite, iconv, json
                    coverage: none

            -   name: Git setup
                if: success()
                run: |
                    git config --local user.email "action@github.com"
                    git config --local user.name "GitHub Action"

            -   name: Install dependencies
                run: |
                    composer global require dragon-code/codestyler
                    composer config repositories.nova composer ${{ secrets.LARAVEL_NOVA_REPOSITORY }}
                    composer require laravel/nova:^${{ matrix.nova.version }}

            -   name: Copy localization files
                run: |
                    cp vendor/laravel/nova/resources/lang/en.json source/nova/${{ matrix.nova.branch }}/nova.json -f
                    cp vendor/laravel/nova/resources/lang/en/validation.php source/nova/${{ matrix.nova.branch }}/validation.php -f

            -   name: Clean up
                run: |
                    composer remove laravel/nova
                    git checkout HEAD -- composer.json

            -   name: Code-Style
                run: codestyle

            -   name: Create a Pull Request
                uses: peter-evans/create-pull-request@v5
                with:
                    branch: projects/patch
                    branch-suffix: random
                    delete-branch: true
                    add-paths: source/nova/${{ matrix.nova.branch }}
                    title: "[source]: Updated Laravel Nova ${{ matrix.nova.branch }} keys"
                    commit-message: üóùÔ∏è Updated Laravel Nova ${{ matrix.nova.branch }} keys
                    body: Updated keys for Laravel Nova ${{ matrix.nova.branch }} üí™
    
    nova_log_viewer:
        uses: Laravel-Lang/.github/.github/workflows/download.yml@main
        strategy:
            fail-fast: true
            matrix:
                version: [ "main" ]
        with:
            project: Laravel Nova Log Viewer ${{ matrix.version }}
            paths: source/nova/log-viewer/${{ matrix.version }}/*
            commands: |
                vendor/bin/lang download \
                    --url=https://github.com/laravel/nova-log-viewer/archive/refs/heads/${{ matrix.version }}.zip \
                    --project=nova/log-viewer \
                    --ver=${{ matrix.version }}

    nova_dusk_suite:
        uses: Laravel-Lang/.github/.github/workflows/download.yml@main
        strategy:
            fail-fast: true
            matrix:
                version: [ "master" ]
        with:
            project: Laravel Nova Dusk Suite ${{ matrix.version }}
            paths: source/nova/dusk-suite/${{ matrix.version }}/*
            commands: |
                vendor/bin/lang download \
                    --url=https://github.com/laravel/nova-dusk-suite/archive/refs/heads/${{ matrix.version }}.zip \
                    --project=nova/dusk-suite \
                    --ver=${{ matrix.version }} \
                    --copy=lang

    spark_aurelius:
        uses: Laravel-Lang/.github/.github/workflows/download.yml@main
        strategy:
            fail-fast: true
            matrix:
                version: [ "11.x", "12.x", "master" ]
        with:
            project: Laravel Spark Aurelius ${{ matrix.version }}
            paths: source/spark/aurelius/${{ matrix.version }}/*
            commands: |
                vendor/bin/lang download \
                    --url=https://github.com/laravel/spark-aurelius/archive/refs/heads/${{ matrix.version }}.zip \
                    --project=spark/aurelius \
                    --ver=${{ matrix.version }} \
                    --copy=install-stubs/resources/lang \
                    --only-copy

    spark_aurelius_mollie:
        uses: Laravel-Lang/.github/.github/workflows/download.yml@main
        strategy:
            fail-fast: true
            matrix:
                version: [ "v2" ]
        with:
            project: Laravel Spark Aurelius Mollie ${{ matrix.version }}
            paths: source/spark/aurelius-mollie/${{ matrix.version }}/*
            commands: |
                vendor/bin/lang download \
                    --url=https://github.com/laravel/spark-aurelius-mollie/archive/refs/heads/${{ matrix.version }}.zip \
                    --project=spark/aurelius-mollie \
                    --ver=${{ matrix.version }} \
                    --copy=install-stubs/resources/lang \
                    --only-copy

    ui:
        uses: Laravel-Lang/.github/.github/workflows/download.yml@main
        strategy:
            fail-fast: true
            matrix:
                version: [ "3.x", "4.x", "master" ]
        with:
            project: Laravel UI ${{ matrix.version }}
            paths: source/ui/${{ matrix.version }}/*
            commands: |
                vendor/bin/lang download \
                    --url=https://github.com/laravel/ui/archive/refs/heads/${{ matrix.version }}.zip \
                    --project=ui \
                    --ver=${{ matrix.version }}
