name: "Code-Style Fixer"

on:
    push:
        branches: [ master ]

jobs:
    fix:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout code
                uses: actions/checkout@v2

            -   name: Checking PHP Syntax
                uses: TheDragonCode/php-codestyler@v1.10.8
                with:
                    github_token: ${{ secrets.COMPOSER_GITHUB_TOKEN }}
                    fix: true
