name: make-todo
on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        name: Keys actualization and generate todo.md

        steps:
            -   name: Checkout code
                uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.0
                    extensions: mbstring, json

            -   name: Git setup
                if: success()
                run: |
                    git config --local user.email "action@github.com"
                    git config --local user.name "GitHub Action"

            -   name: Keys actualization
                if: success()
                run: php script/keys.php

            -   name: Commit files after checking keys
                id: commit_keys
                if: success()
                run: |
                    IS_DIRTY=1

                    { git add . && git commit -a -m "Updating translations keys"; } || IS_DIRTY=0

                    echo ::set-output name=is_dirty::${IS_DIRTY}

            -   name: Generate todo.md
                if: success()
                run: php script/todo.php

            -   name: Commit file
                id: commit_todo
                if: success()
                run: |
                    IS_DIRTY=1

                    { git add . && git commit -a -m "Updated todo.md file"; } || IS_DIRTY=0

                    echo ::set-output name=is_dirty::${IS_DIRTY}

            -   name: Push changes
                uses: ad-m/github-push-action@master
                if: success() && (steps.commit_keys.outputs.is_dirty == 1 || steps.commit_todo.outputs.is_dirty == 1)
                with:
                    github_token: ${{ secrets.GITHUB_TOKEN }}
