name: update
on:
    schedule:
        -   cron: 0 0 * * *
    push:
        branches:
            - main
    create:
        tags:

jobs:
    update:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout code
                uses: actions/checkout@v3

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    extensions: curl, mbstring, zip, pcntl, pdo, pdo_sqlite, iconv, json
                    coverage: none

            -   name: Git setup
                if: success()
                run: |
                    git config --local user.email "action@github.com"
                    git config --local user.name "GitHub Action"

            -   name: Install dependencies
                run: composer update --prefer-stable --prefer-dist --no-progress --no-interaction

            -   name: Scanning packages
                id: packages
                if: success()
                run: |
                    IS_DIRTY=1

                    php app/packages.php

                    { git add . && git commit -a -m "Updating package files"; } || IS_DIRTY=0

                    echo ::set-output name=is_dirty::${IS_DIRTY}

            -   name: Keys actualization
                id: keys
                if: success()
                run: |
                    IS_DIRTY=1

                    php app/keys.php

                    { git add . && git commit -a -m "Updating translations keys"; } || IS_DIRTY=0

                    echo ::set-output name=is_dirty::${IS_DIRTY}

            -   name: Updating referents
                id: referents
                if: success()
                run: |
                    IS_DIRTY=1

                    php app/referents.php

                    { git add . && git commit -a -m "Updating the docs/referents.md file"; } || IS_DIRTY=0

                    echo ::set-output name=is_dirty::${IS_DIRTY}

            -   name: Checking for excludes
                id: excludes
                if: success()
                run: |
                    IS_DIRTY=1

                    php app/excludes.php

                    { git add . && git commit -a -m "Updating excludes files"; } || IS_DIRTY=0

                    echo ::set-output name=is_dirty::${IS_DIRTY}

            -   name: Update statuses
                id: status
                if: success()
                run: |
                    IS_DIRTY=1

                    php app/status.php

                    { git add . && git commit -a -m "Updated status of translations"; } || IS_DIRTY=0

                    echo ::set-output name=is_dirty::${IS_DIRTY}

            -   name: Update changelog
                uses: stefanzweifel/changelog-updater-action@v1
                if: success() && startsWith(github.ref, 'refs/tags/')
                with:
                    latest-version: ${{ github.event.release.tag_name }}
                    release-notes: ${{ github.event.release.body }}
                    compare-url-target-revision: ${{ github.event.release.target_commitish }}
                    path-to-changelog: docs/changelog/10.x.md

            -   name: Storing changelog
                id: changelog
                if: success()
                run: |
                    IS_DIRTY=1

                    { git add . && git commit -a -m "Update CHANGELOG ðŸ§¾"; } || IS_DIRTY=0

                    echo ::set-output name=is_dirty::${IS_DIRTY}

            -   name: Push changes
                uses: ad-m/github-push-action@master
                if: |
                    success() && (
                    steps.excludes.outputs.is_dirty == 1 ||
                    steps.keys.outputs.is_dirty == 1 ||
                    steps.packages.outputs.is_dirty == 1 ||
                    steps.referents.outputs.is_dirty == 1 ||
                    steps.status.outputs.is_dirty == 1 ||
                    steps.changelog.outputs.is_dirty == 1
                    )
                with:
                    github_token: ${{ secrets.COMPOSER_TOKEN }}

            -   name: Generate Docs Trigger
                uses: myrotvorets/trigger-repository-dispatch-action@1.1.1
                if: success()
                with:
                    token: ${{ secrets.COMPOSER_TOKEN }}
                    repo: Laravel-Lang/lang
                    type: generate-docs

